### ISSUE TITLE
Add examples of how to use this tool

### ISSUE THREAD

**Issue by robkinyon** [awanninger/fails#2]
There is no explanation of how to use the results of 'fails generate' and 'fails new'. Your documentation needs to say, at least, that you will be using Rake to execute the tests.

**Comment by awanninger** [comment]
Fixed in commit [b5eaa02](https://github.com/awanninger/fails/commit/b5eaa02994294adfcfc021fd9c8d0130bc178d02)

**Comment by awanninger** [comment]
Fixed in commit [b5eaa02](https://github.com/awanninger/fails/commit/b5eaa02994294adfcfc021fd9c8d0130bc178d02)
